# VectorLint GitHub Action
# 
# AI-powered content linting for Markdown files using LLMs.
# Uses the vectorlint npm package: https://www.npmjs.com/package/vectorlint

name: 'VectorLint'
description: 'AI-powered content linting for Markdown files using LLMs (OpenAI, Anthropic, Gemini)'
author: 'TRocket Labs'

inputs:
  github_token:
    description: 'GitHub token for reviewdog'
    required: false
    default: ${{ github.token }}
  
  gemini_api_key:
    description: 'Google Gemini API key'
    required: false
  
  openai_api_key:
    description: 'OpenAI API key'
    required: false
  
  anthropic_api_key:
    description: 'Anthropic API key'
    required: false
  
  reporter:
    description: 'Reporter type (github-pr-check, github-pr-review, github-check)'
    required: false
    default: 'github-pr-check'
  
  filter_mode:
    description: 'Filter mode (added, diff_context, file, nofilter)'
    required: false
    default: 'added'
  
  fail_on_error:
    description: 'Fail if errors are found'
    required: false
    default: 'true'
  
  vectorlint_flags:
    description: 'Additional flags to pass to vectorlint'
    required: false
    default: ''
  
  llm_provider:
    description: 'LLM provider (openai, anthropic, gemini, azure-openai)'
    required: false
    default: 'anthropic'

  vectorlint_version:
    description: 'VectorLint npm package version (e.g., latest, 1.0.0)'
    required: false
    default: 'latest'
  
  tool_name:
    description: 'Name of the tool/check'
    required: false
    default: 'vectorlint'
  
  # Azure OpenAI Configuration
  azure_openai_api_key:
    description: 'Azure OpenAI API key'
    required: false
  
  azure_openai_endpoint:
    description: 'Azure OpenAI endpoint URL'
    required: false
  
  azure_openai_deployment_name:
    description: 'Azure OpenAI deployment name'
    required: false
  
  azure_openai_api_version:
    description: 'Azure OpenAI API version (e.g., 2024-02-15-preview)'
    required: false
  
  # API Keys for additional providers
  perplexity_api_key:
    description: 'Perplexity API key for search functionality'
    required: false
  
  # Model Configuration
  openai_model:
    description: 'OpenAI model to use (e.g., gpt-4, gpt-3.5-turbo)'
    required: false
  
  anthropic_model:
    description: 'Anthropic model to use (e.g., claude-3-opus-20240229)'
    required: false
  
  anthropic_max_tokens:
    description: 'Max tokens for Anthropic responses'
    required: false
  
  gemini_model:
    description: 'Gemini model to use'
    required: false
  
  azure_openai_model:
    description: 'Azure OpenAI model deployment name'
    required: false
  
  # Temperature Configuration
  openai_temperature:
    description: 'Temperature setting for OpenAI (0.0-2.0)'
    required: false
  
  anthropic_temperature:
    description: 'Temperature setting for Anthropic (0.0-1.0)'
    required: false
  
  gemini_temperature:
    description: 'Temperature setting for Gemini (0.0-2.0)'
    required: false
  
  azure_openai_temperature:
    description: 'Temperature setting for Azure OpenAI (0.0-2.0)'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'check-circle'
  color: 'blue'
